name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install angular-cli
        run: npm install -g @angular/cli

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build database
        run: |
          git clone --depth 1 https://codeberg.org/HellLord77/infinite-craft-data.git data
          sqlite3 data.sqlite " \
          CREATE TABLE element ( \
            id INTEGER PRIMARY KEY AUTOINCREMENT, \
            text TEXT UNIQUE NOT NULL, \
            emoji TEXT NOT NULL \
          ); \
          CREATE TABLE pair ( \
            first_id INTEGER NOT NULL, \
            second_id INTEGER NOT NULL, \
            result_id INTEGER NOT NULL, \
            PRIMARY KEY (first_id, second_id), \
            FOREIGN KEY (first_id) REFERENCES element (id), \
            FOREIGN KEY (second_id) REFERENCES element (id), \
            FOREIGN KEY (result_id) REFERENCES element (id) \
          ); \
          "
          tail -n +2 -q data/element/*.csv >> data/element.csv
          sqlite3 data.sqlite ".mode csv" ".import data/element.csv element"
          tail -n +2 -q data/pair/*.csv >> data/pair.csv
          sqlite3 data.sqlite ".mode csv" ".import data/pair.csv pair"
          sqlite3 data.sqlite " \
          DELETE \
          FROM pair \
          WHERE result_id = (SELECT id FROM element WHERE text = 'Nothing'); \
          VACUUM; \
          "
          mv data.sqlite public/data.sqlite
          rm -rf data

      - name: Install dependencies
        run: npm install

      - name: Build static files
        id: build
        run: ng build --base-href=./

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/browser

  deploy:
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
